### ISSUE TITLE
duplicate lines in iptables config

### ISSUE THREAD

**Issue by PetrJ-v** [chucklessducks/VPS-Wireguard-Nginx-Mailcow#2]
There are 8 identical lines in iptables config on MailCow Setup page
<img width="934" alt="Снимок экрана 2022-07-21 в 02 52 28" src="https://user-images.githubusercontent.com/35663968/180101748-05568bb9-5d5c-4ddc-ac79-de6991bee78b.png">
That is how it should be?

**Comment by chucklessducks** [comment]
Yes, I am not sure why but that is what the guide said to do so I did it. You prob could just do one.

**Comment by PetrJ-v** [comment]
Thanks for the answer. I'll try with one first.
